// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_UZBRuqDIdG-0wWw7-C4vC7aCenuUoqk',
    appId: '1:471754522056:web:b0e1543f71942d2d5ad4fd',
    messagingSenderId: '471754522056',
    projectId: 'dumyimage',
    authDomain: 'dumyimage.firebaseapp.com',
    databaseURL: 'https://dumyimage-default-rtdb.firebaseio.com',
    storageBucket: 'dumyimage.appspot.com',
    measurementId: 'G-1MKKLDP0XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6Gy3vnnobEG_ElhuNX5N052ole0mo-U',
    appId: '1:471754522056:android:9ca947eeeb913ee25ad4fd',
    messagingSenderId: '471754522056',
    projectId: 'dumyimage',
    databaseURL: 'https://dumyimage-default-rtdb.firebaseio.com',
    storageBucket: 'dumyimage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTxbFige33bB7TC7zXgPWhPuc5rytPMU',
    appId: '1:471754522056:ios:e3941cb31d0da41a5ad4fd',
    messagingSenderId: '471754522056',
    projectId: 'dumyimage',
    databaseURL: 'https://dumyimage-default-rtdb.firebaseio.com',
    storageBucket: 'dumyimage.appspot.com',
    iosClientId: '471754522056-98cbr9ss96oi2jlmo1tt8cmrfugp8qu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoCopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTxbFige33bB7TC7zXgPWhPuc5rytPMU',
    appId: '1:471754522056:ios:e3941cb31d0da41a5ad4fd',
    messagingSenderId: '471754522056',
    projectId: 'dumyimage',
    databaseURL: 'https://dumyimage-default-rtdb.firebaseio.com',
    storageBucket: 'dumyimage.appspot.com',
    iosClientId: '471754522056-98cbr9ss96oi2jlmo1tt8cmrfugp8qu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoCopy',
  );
}
